#!/bin/bash

echo "== Outer job status =="

qstat -u $(\whoami)

echo "Current system status is:"

echo "== Running =="
ls dirrunning/run*/cmd

echo "== ToDo =="
ls dirtodo/run*/cmd

echo "== Done =="
ls dirdone/run*/cmd

echo ==
