#!/bin/bash

echo "== Outer job status =="

qstat -u $(\whoami) 2>/dev/null

echo "Current system status is:"

echo "== Running =="
ls dirrunning/run*/cmd 2>/dev/null

echo "== ToDo =="
ls dirtodo/run*/cmd 2>/dev/null

echo "== Done =="
ls dirdone/run*/cmd 2>/dev/null

echo ==
