#!/bin/bash

usage() { echo "Usage: $0 [-f <inputfile>] -e <executable>" 1>&2; exit 1; }

gendirs()
{
    if [ ! -f .counter ]; then
        echo "reset requried"
	exit 1
    fi

    oldcount=$(head -1 .counter)
    expr $oldcount + 1 > .counter
    count=$(head -1 .counter)
    mkdir -p dirtodo/run"$count"/infiles
    mkdir -p dirtodo/run"$count"/cmd
}

while getopts ":f:e:" o; do
case "${o}" in
  f)
      infile=${OPTARG}
      ;;
  e)
      exec=${OPTARG}
      ;;
  *)
      usage
      ;;
esac
done

gendirs

cd dirtodo/run$count/cmd

ln -s $exec $(basename $exec)

cd -
