#!/bin/bash

#set -x

finish=0
trap 'finish=1' SIGUSR1

while (( finish != 1 ))
do
    task=$(/bin/ls -1 dirtodo/cmd|head -n 1)
    taskargs=$(awk -v "r=$task" '{if ($1==r){ $1="";print $0}}' ./config)
    if [ -f dirtodo/$task ] ; then
       runjob --block $COBALT_PARTNAME --ranks-per-node 1 : dirtodo/cmd/$task $taskargs
       mv dirtodo/cmd/$task dirdone/cmd/
       echo "=== ${task} : Done. ==="
    fi
    sleep 1
done
