#!/bin/bash

#set -x

echo "My pid is: $$"
finish=0
trap 'finish=1' SIGUSR1

while (( finish != 1 ))
do
    task=$(/bin/ls -1 todo/|head -n 1)
    if [ -f todo/$task ] ; then
       sh todo/$task
       mv todo/$task dirdone
    else
       echo "."
    fi
    sleep 1
done
